name: Deploy Application

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test Build
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'

      - name: Install common dependencies
        run: |
          npm install

      - name: Install and Build Backend
        working-directory: backend
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_IP: ${{ secrets.DB_IP }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

        run: |
          npm install
          npm run build

      - name: Install and Build Frontend
        working-directory: frontend
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: |
          npm install
          npm run build
